// CJS shim — exposes Node.js / Electron APIs for ESM renderer modules
window.electronShim = {
    ipcRenderer: require('electron').ipcRenderer,
    shell: require('electron').shell,
    remote: require('@electron/remote'),
    Store: require('electron-store').default,
    pkg: require('../../../../package.json'),
    translations: {
        'en-US': require('../../../translation/en-US'),
        'af-ZA': require('../../../translation/af-ZA'),
        'ar-SA': require('../../../translation/ar-SA'),
        'bn-BD': require('../../../translation/bn-BD'),
        'ca-ES': require('../../../translation/ca-ES'),
        'cs-CZ': require('../../../translation/cs-CZ'),
        'da-DK': require('../../../translation/da-DK'),
        'de-DE': require('../../../translation/de-DE'),
        'el-GR': require('../../../translation/el-GR'),
        'es-ES': require('../../../translation/es-ES'),
        'fi-FI': require('../../../translation/fi-FI'),
        'fr-FR': require('../../../translation/fr-FR'),
        'he-IL': require('../../../translation/he-IL'),
        'hu-HU': require('../../../translation/hu-HU'),
        'it-IT': require('../../../translation/it-IT'),
        'ja-JP': require('../../../translation/ja-JP'),
        'ko-KR': require('../../../translation/ko-KR'),
        'nb-NO': require('../../../translation/nb-NO'),
        'nl-NL': require('../../../translation/nl-NL'),
        'pl-PL': require('../../../translation/pl-PL'),
        'pt-BR': require('../../../translation/pt-BR'),
        'ro-RO': require('../../../translation/ro-RO'),
        'ru-RU': require('../../../translation/ru-RU'),
        'sr-RS': require('../../../translation/sr-RS'),
        'sv-SE': require('../../../translation/sv-SE'),
        'tr-TR': require('../../../translation/tr-TR'),
        'uk-UA': require('../../../translation/uk-UA'),
        'vi-VN': require('../../../translation/vi-VN'),
        'zh-CN': require('../../../translation/zh-CN'),
        'zh-TW': require('../../../translation/zh-TW'),
    },
};
